### ISSUE TITLE
Error running example

### ISSUE THREAD

**Issue by taciturnaxolotl** [robherley/guesslang-go#3]
When I run the example, I get the following error:

```bash
# github.com/galeone/tensorflow/tensorflow/go/op
../../../go/pkg/mod/github.com/galeone/tensorflow/tensorflow/go@v0.0.0-20221023090153-6b7fa0680c3e/op/scope.go:36:26: undefined: tf.Graph
../../../go/pkg/mod/github.com/galeone/tensorflow/tensorflow/go@v0.0.0-20221023090153-6b7fa0680c3e/op/scope.go:39:28: undefined: tf.Operation
../../../go/pkg/mod/github.com/galeone/tensorflow/tensorflow/go@v0.0.0-20221023090153-6b7fa0680c3e/op/scope.go:55:30: undefined: tf.Graph
../../../go/pkg/mod/github.com/galeone/tensorflow/tensorflow/go@v0.0.0-20221023090153-6b7fa0680c3e/op/scope.go:62:33: undefined: tf.Graph
../../../go/pkg/mod/github.com/galeone/tensorflow/tensorflow/go@v0.0.0-20221023090153-6b7fa0680c3e/op/scope.go:75:38: undefined: tf.OpSpec
../../../go/pkg/mod/github.com/galeone/tensorflow/tensorflow/go@v0.0.0-20221023090153-6b7fa0680c3e/op/scope.go:75:50: undefined: tf.Operation
../../../go/pkg/mod/github.com/galeone/tensorflow/tensorflow/go@v0.0.0-20221023090153-6b7fa0680c3e/op/scope.go:115:52: undefined: tf.Operation
../../../go/pkg/mod/github.com/galeone/tensorflow/tensorflow/go@v0.0.0-20221023090153-6b7fa0680c3e/op/gradients.go:33:37: undefined: tf.Output
../../../go/pkg/mod/github.com/galeone/tensorflow/tensorflow/go@v0.0.0-20221023090153-6b7fa0680c3e/op/op.go:33:56: undefined: tf.Output
../../../go/pkg/mod/github.com/galeone/tensorflow/tensorflow/go@v0.0.0-20221023090153-6b7fa0680c3e/op/wrappers.go:15:28: undefined: tf.Operation
../../../go/pkg/mod/github.com/galeone/tensorflow/tensorflow/go@v0.0.0-20221023090153-6b7fa0680c3e/op/wrappers.go:15:28: too many errors
```

I'm on `NixOS 24.05.20241106.dba4149 (Uakari) x86_64` if thats any help :)

**Comment by taciturnaxolotl** [comment]
@robherley pinging you because ik especially with my smaller projects I never notice issues till 8 months later unless someone pings me :)

**Comment by robherley** [comment]
👋 @kcoderhtml 

I'm not sure why you are having issues, maybe it's related to cgo? Can you run `go env CGO_ENABLED GCCGO CC`

For instance, the Graph struct is defined here in the library:
- https://github.com/galeone/tensorflow/blob/6b7fa0680c3e88faec9c1491d3273b8ce9e7b1bd/tensorflow/go/graph.go#L51-L54

I'm not super familiar with nix, are you using nix-shell?

I found this issue that _might_ be what you're seeing:
- https://discourse.nixos.org/t/go-weirdness-with-nix-shell/52422

**Comment by taciturnaxolotl** [comment]
just realized i never responded to this 😭

**Comment by taciturnaxolotl** [comment]
I tried that but never could get it to work; I ended up just writing a simple python server (https://github.com/taciturnaxolotl/guesslang) that runs an api that I can call instead. Not the most elegant solution but it does work
